#Requires -Version 5.1

<#
.SYNOPSIS
    Teams: HTML report of Teams apps
.DESCRIPTION
    Generates an HTML report with app information from the Teams tenant app store.
.PARAMETER AppId
    The app's ID generated by Teams
.PARAMETER ExternalID
    The external ID of the app from Azure AD
.PARAMETER DisplayName
    Name of the app visible to users
.PARAMETER DistributionMethod
    The type of app (organization or global)
.EXAMPLE
    PS> ./Get-MSTTeamsApp-Html.ps1 | Out-File report.html
.EXAMPLE
    PS> ./Get-MSTTeamsApp-Html.ps1 -DistributionMethod "organization" | Out-File report.html
.CATEGORY O365
#>

[CmdletBinding()]
Param(
    [string]$AppId,
    [string]$ExternalID,
    [string]$DisplayName,
    [ValidateSet('organization','global')]
    [string]$DistributionMethod
)

Process {
    try {
        [hashtable]$cmdArgs = @{'ErrorAction' = 'Stop'}
        if ($PSBoundParameters.ContainsKey('AppId')) { $cmdArgs.Add('Id', $AppId) }
        if ($PSBoundParameters.ContainsKey('ExternalID')) { $cmdArgs.Add('ExternalID', $ExternalID) }
        if ($PSBoundParameters.ContainsKey('DisplayName')) { $cmdArgs.Add('DisplayName', $DisplayName) }
        if ($PSBoundParameters.ContainsKey('DistributionMethod')) { $cmdArgs.Add('DistributionMethod', $DistributionMethod) }

        $result = Get-TeamsApp @cmdArgs | Select-Object * | Sort-Object -Property DisplayName

        if ($null -eq $result -or $result.Count -eq 0) {
            Write-Output "No Teams apps found"
            return
        }

        Write-Output ($result | ConvertTo-Html -Fragment)
    }
    catch { throw }
}
