#Requires -Version 5.1

<#
.SYNOPSIS
    Teams: Updates an app in the Teams tenant app store
.DESCRIPTION
    Updates an existing app in the Teams tenant app store with a new manifest zip file.
.PARAMETER AppId
    The app's ID generated by Teams (different from the external ID)
.PARAMETER AppPath
    The local path of the app manifest zip file
.EXAMPLE
    PS> ./Set-MSTTeamsApp.ps1 -AppId "app-guid" -AppPath "C:\temp\updated-app.zip"
.CATEGORY O365
#>

[CmdletBinding()]
Param(
    [Parameter(Mandatory = $true)]
    [string]$AppId,
    [Parameter(Mandatory = $true)]
    [string]$AppPath
)

Process {
    try {
        [hashtable]$cmdArgs = @{'ErrorAction' = 'Stop'; 'Id' = $AppId; 'Path' = $AppPath}

        $null = Set-TeamsApp @cmdArgs
        $result = Get-TeamsApp -Id $AppId -ErrorAction Stop | Select-Object *

        if ($null -eq $result) {
            Write-Output "Failed to update Teams app"
            return
        }
        $result | Add-Member -NotePropertyName Timestamp -NotePropertyValue (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') -PassThru -Force
    }
    catch { throw }
}
